### ISSUE TITLE
AssertionError after starting the script

### ISSUE THREAD

**Issue by lupo49** [hoxu/dokuwiki2git#1]
Hi,

I tried the script on my DokuWiki installation. The following output comes up:

/dokuwiki2git$ ./dokuwiki2git -o foo/ wiki/data/
INFO - Using datadir: wiki/data/
INFO - Reading meta
Traceback (most recent call last):
  File "./dokuwiki2git", line 187, in <module>
    c.run(sys.argv[1:])
  File "./dokuwiki2git", line 169, in run
    self.read_data()
  File "./dokuwiki2git", line 102, in read_data
    self.read_meta()
  File "./dokuwiki2git", line 133, in read_meta
    self.read_meta_page(pagepath, os.path.join(path, f))
  File "./dokuwiki2git", line 147, in read_meta_page
    assert(changeparts[3] == pagename)
AssertionError

Any ideas what is wrong here?

**Comment by hoxu** [comment]
Try running the script with -v.

The asserts are there for sanity checking that the input is as dokuwiki2git expects it to be, most likely there is some case of filename<->pagename mapping that dokuwiki2git does not yet understand.

**Comment by lupo49** [comment]
This is the last line before it stops:

DEBUG - ['1236179785', '195.145.112.149', 'C', 'task:XXXXXXXXXXX_dokumentation_-_migration_einer_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.doc', 'lupo49', '', '\n']
Traceback (most recent call last):
  File "./dokuwiki2git", line 187, in <module>
    c.run(sys.argv[1:])
  File "./dokuwiki2git", line 169, in run
    self.read_data()
  File "./dokuwiki2git", line 102, in read_data
    self.read_meta()
  File "./dokuwiki2git", line 133, in read_meta
    self.read_meta_page(pagepath, os.path.join(path, f))
  File "./dokuwiki2git", line 147, in read_meta_page
    assert(changeparts[3] == pagename)
AssertionError

**Comment by hoxu** [comment]
Closing this issue - seemed that the problem was that the dokuwiki data directory had been manually edited, and because of that dokuwiki2git has no way to recover from certain situations.

**Comment by pomeo** [comment]
I have a similar error:
./dokuwiki2git -v ./dokuwiki/data 
INFO - Using datadir: /home/pomeo/www/github/dokuwiki2git/dokuwiki/data
INFO - Reading users.auth.php
DEBUG - (remove admin data)
INFO - Read 1 users
INFO - Reading meta
DEBUG - Reading meta for page "%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B0"
DEBUG - ['1369332667', '176.114.224.2', 'C', '\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0', 'pomeo', 'created', '\n']
Traceback (most recent call last):
  File "./dokuwiki2git", line 205, in <module>
    c.run(sys.argv[1:])
  File "./dokuwiki2git", line 187, in run
    self.read_data()
  File "./dokuwiki2git", line 107, in read_data
    self.read_meta()
  File "./dokuwiki2git", line 138, in read_meta
    self.read_meta_page(pagepath, os.path.join(path, f))
  File "./dokuwiki2git", line 152, in read_meta_page
    assert(changeparts[3] == pagename)
AssertionError

**Comment by pomeo** [comment]
My fix
https://github.com/pomeo/dokuwiki2git/commit/51994af44ad36e6dbe1759bbaa854e4405f2224e
and for gollum
https://github.com/pomeo/dokuwiki2git/commit/0d5c84a32e19174621dd05b8f3cf7411c6fc84d4
