### ISSUE TITLE
AssertionError converting

### ISSUE THREAD

**Issue by nerdoc** [hoxu/dokuwiki2git#7]
```
dokuwiki2git  example.com/data/
INFO - Using datadir: ..../example.com/data
INFO - Reading users.auth.php
INFO - Read 2 users
INFO - Reading meta
Traceback (most recent call last):
  File "dokuwiki2git/dokuwiki2git", line 205, in <module>
    c.run(sys.argv[1:])
  File "dokuwiki2git/dokuwiki2git", line 187, in run
    self.read_data()
  File "dokuwiki2git/dokuwiki2git", line 107, in read_data
    self.read_meta()
  File "dokuwiki2git/dokuwiki2git", line 138, in read_meta
    self.read_meta_page(pagepath, os.path.join(path, f))
  File "dokuwiki2git/dokuwiki2git", line 152, in read_meta_page
    assert(changeparts[3] == pagename)
AssertionError

```
Did I make a mistake when calling dokuwiki2git - or is there a bug?
Any info I can provide more?

**Comment by Epy** [comment]
Hello
I guess dokuwiki changed a lot since this script (not modified in 3 years), had a similar error when I last tried a month ago (and didn't had time to find why)
